Repository equinor/energyvision, pull requests merged in 2024-08, with the labels that each got.

#2438 :bug: Fixed label translations #2430
  web/pageComponents/topicPages/Form/CareerFairForm.tsx
Labels: 🐛 bug

#2426 🔍️ Better SEO warnings in sanity #750
  sanityv3/schemas/objects/titleAndMeta.tsx
Labels: 📈 seo

#2425 🏗️ add nvmrc file to project #2085
  .nvmrc
Labels: 🛠 technical
